services: 
  postgres:
    image: 'postgres:latest'
    container_name: 'spring-postgres'
    enviroment:
      - 'POSTGRES_DB=springdb'
      - 'POSTGRES_PASSWORD=springpassword'
      - 'POSTGRES_USER=springuser'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    restart: 'unless-stopped'
volume:
  postgres-data:
